// Rebuild `../fixtures/pinned-documents.ts` from the documents themselves.
//
//   bun skills/iso-24495-5/tests/reference/build-pinned-documents.ts
//
// It prints the line counts and rewrites the fixture in place. Run it from the
// repository root, in the same commit as any edit to a document it covers.
//
// The fixture holds these documents whole rather than in pieces. Six rounds of
// adversarial review taught that lesson twice over. First inside the text: a
// pinned phrase leaves every other phrase of its sentence deletable, so the
// expectations became whole blocks. Then around it: a whole block says nothing
// about the lines on either side of it, and a reviewer wrapped a pinned
// paragraph in image syntax so that it rendered as alternative text, and in a
// link title so that it rendered as an attribute. The text was intact, the
// gate was green, and a browser showed neither.
//
// Guarding the space around a block needs the whole file, and nothing less
// does. That is the cost this file exists to pay: editing one of these
// documents means running this script in the same commit.
//
// This script is checked in because the last generator was not. A reviewer
// twice said a claim about a script nobody could run was unsupported, and was
// right both times.

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { shippedDocuments } from "./shipped-documents.ts";

const REPOSITORY_ROOT = join(import.meta.dir, "..", "..", "..", "..");
const FIXTURE = join(import.meta.dir, "..", "fixtures", "pinned-documents.ts");

const entries = shippedDocuments(REPOSITORY_ROOT).map((file) => {
  const lines = readFileSync(join(REPOSITORY_ROOT, file), "utf8").split(/\r?\n/);
  console.log(`${file}: ${lines.length} lines`);
  const body = lines.map((line) => `    ${JSON.stringify(line)},`).join("\n");
  return `  ${JSON.stringify(file)}: [\n${body}\n  ],`;
}).join("\n");

const contents = `// Generated by ../reference/build-pinned-documents.ts. Do not edit by hand.
//
// Every line of every document this repository pins. Run the builder in the
// same commit as any edit to one of them, and read the diff here as the record
// of what a reader's page gained or lost.

export const PINNED_DOCUMENT_TEXT: Record<string, string[]> = {
${entries}
};
`;

writeFileSync(FIXTURE, contents.replace(/\n/g, "\r\n"), "utf8");
console.log(`wrote ${FIXTURE}`);
